version: '3.8'
services:
  ck-backend:
    env_file:
      - .env
    image: ck-backend
    pull_policy: build
    build:
      dockerfile: ./Dockerfile
      no_cache: true
    ports:
      - 1112:3000